export const queryConfig = {
  LOGIN: "/auth/login",
  REGISTER: "/auth/register",
  LOGOUT: "/auth/logout",
  GET_ACCESS_TOKEN: "/auth/get-access-token",
  GET_TEMPLATE_THEMES: "/template-themes",
  REMOVE_TEMPLATE_IMG: "/template-img",
  SEARCH_TEMPLATE: "/templates-search",
  CURD_TEMPLATES: "/templates",
  GET_QUESTION_TYPES: "/question-types",
  CURD_QUESTION: "/questions",
  UPDATE_QUESTIONS_ORDERS: "/questions-order",
  CURD_OPTION: "/options",
  UPDATE_OPTIONS_ORDER: "/options-orders",
  CRUD_FORMS: "/forms",
  CURD_ANSWER: "/answers",
  CRUD_ANSWER_OPTIONS: "/answer-options",
  CRUD_USERS: "/users",
  CRUD_COMMENTS: "/template/comments",
  CRUD_TEMPLATE_LIKES: "/template/likes",
  CRUD_COMMENT_LIKES: "/comment/likes",
};
