export const queryConfig = {
  LOGIN: "/auth/login",
  REGISTER: "/auth/register",
  LOGOUT: "/auth/logout",
  GET_TEMPLATES: "/templates",
  GET_TEMPLATE: "/templates",
  GET_TEMPLATE_THEMES: "/template-themes",
  REMOVE_TEMPLATE_IMG: "/template-img",
  CREATE_TEMPLATE: "/templates",
  UPDATE_TEMPLATE: "/templates",
  GET_QUESTIONS: "/questions",
  GET_QUESTION_TYPES: "/question-types",
  CREATE_QUESTION: "/questions",
  UPDATE_QUESTION: "/questions",
  GET_OPTIONS: "/options",
  CREATE_OPTION: "/options",
  UPDATE_OPTION: "/options",
};
